/**
 * AI Stack Simulator — pure computation engine.
 *
 * Models LLM stacks across nine scale steps (1k → 1M users), producing
 * monthly cost, token-aware latency, per-layer cost composition, breaking
 * points, kill conditions, rate-limit ceilings, and a bottleneck verdict.
 *
 * The engine is pure: callers pass in the tool catalog. The /simulate
 * page loads tools from Supabase and runs simulate() entirely client-side
 * so sliders update results instantly.
 */

import type { Tool } from "@/lib/types";

// ── Public types ──────────────────────────────────────────────────────────────

export type SimulationUseCase = "chatbot" | "rag" | "agent" | "custom";

export interface SimulationInput {
  useCase: SimulationUseCase;
  monthlyUsers: number;
  requestsPerUserPerDay: number;
  /** Tokens of input per request (prompt + retrieved context + system). */
  avgInputTokens: number;
  /** Tokens generated by the model per request. */
  avgOutputTokens: number;
  /** Fraction of input tokens served from prompt cache (0–1). 90% discount on the cached portion. */
  cacheHitRate?: number;
  /** Fraction of traffic that can run via batch API (0–1). 50% discount on input + output. */
  batchPct?: number;
  /** RAG only — total stored vectors. Used to project vector-DB storage cost. */
  vectorCount?: number;
  /** RAG only — tokens of query sent to the embedding model per request (default 80). */
  embeddingTokensPerQuery?: number;
  /** Peak/average request ratio (default 3×). Drives rate-limit checks. */
  peakToAverageRatio?: number;
  stack: {
    llm: string;
    embedding?: string;
    vectorDb?: string;
    framework?: string;
    eval?: string;
    guardrails?: string;
    /** Cheap LLM the router sends a fraction of traffic to. */
    routerCheapLlm?: string;
    /** Fraction routed to the cheap model (0–1). */
    routerCheapPct?: number;
  };
}

export interface CostByLayer {
  llm: number;
  embedding: number;
  vector: number;
  framework: number;
  eval: number;
  guardrails: number;
}

export interface LatencyByStage {
  /** Pre-request guardrails check */
  guardrails: number;
  /** Query embedding generation */
  embedding: number;
  /** Vector retrieval */
  vector: number;
  /** LLM time-to-first-token */
  ttft: number;
  /** LLM output generation (output_tokens / throughput) */
  generation: number;
  /** Framework / orchestration overhead */
  framework: number;
}

export interface SimulationSnapshot {
  users: number;
  monthlyRequests: number;
  monthlyCostUSD: number;
  costPerRequest: number;
  costPerUser: number;
  avgLatencyMs: number;
  /** Per-tool monthly cost in USD — feeds the per-tool line chart. */
  costBreakdown: Record<string, number>;
  /** Per-layer monthly cost in USD — feeds the composition donut. */
  costByLayer: CostByLayer;
  /** Per-stage latency in ms — drives the latency-breakdown panel. */
  latencyByStage: LatencyByStage;
  /** Legacy mirror of latencyByStage for older UI bits. */
  latencyBreakdown: Record<string, number>;
}

export interface BreakingPoint {
  users: number;
  type: "latency" | "cost" | "architecture" | "rate_limit";
  message: string;
  recommendation?: string;
}

export interface KillCondition {
  type: string;
  message: string;
  recommendation?: string;
}

export type BottleneckType = "cost" | "latency" | "rate_limit" | "balanced" | "none";

export interface SimulationResult {
  snapshots: SimulationSnapshot[];
  breakingPoints: BreakingPoint[];
  killConditions: KillCondition[];
  bottleneck: BottleneckType;
  bottleneckMessage: string;
  /** First scale step at which TPM or RPM is exceeded. null if never. */
  rateLimitAtUsers: number | null;
}

// ── Scale steps ───────────────────────────────────────────────────────────────

export const SCALE_STEPS = [
  1_000, 5_000, 10_000, 25_000, 50_000, 100_000, 250_000, 500_000, 1_000_000,
];

// ── Per-use-case token defaults ───────────────────────────────────────────────

export const TOKEN_DEFAULTS: Record<
  SimulationUseCase,
  { inputTokens: number; outputTokens: number }
> = {
  chatbot: { inputTokens: 400, outputTokens: 600 },
  rag: { inputTokens: 3_000, outputTokens: 400 },
  agent: { inputTokens: 1_500, outputTokens: 800 },
  custom: { inputTokens: 1_000, outputTokens: 500 },
};

// ── Latency ceilings — when do we flag "this stack is too slow" ──────────────
//
// 2s is unrealistic in 2026: a typical Sonnet-class model at 50 tok/s producing
// 600 output tokens is already at 12s. Use-case-aware ceilings reflect what
// users actually tolerate: chatbots need to feel snappy, RAG users accept a
// retrieval pause, agent loops are knowingly slow.

const LATENCY_CEILING_MS: Record<SimulationUseCase, number> = {
  chatbot: 8_000,
  rag: 12_000,
  agent: 25_000,
  custom: 10_000,
};

/** Time-to-first-token "feels slow" threshold — independent of total length. */
const TTFT_SLOW_MS = 1_500;

// ── Layer defaults (when a tool has no published value) ───────────────────────

const DEFAULTS = {
  /** Time-to-first-token fallback for LLMs with no ttft data. */
  ttftMs: 600,
  /** Output tokens/sec fallback for LLMs with no throughput data. */
  throughputTokPerSec: 50,
  /** Vector retrieval p50 ms when not specified. */
  vectorMs: 80,
  /** Framework overhead p50 ms when not specified. */
  frameworkMs: 100,
  /** Guardrails check p50 ms when not specified. */
  guardrailsMs: 60,
  /** Query embedding generation p50 ms (small input, fast). */
  embeddingMs: 90,
  /** Embedding-tokens-per-query fallback (small RAG query). */
  embeddingTokensPerQuery: 80,
  /** Default embedding cost when no embedding tool is set (text-embedding-3-small price). */
  embeddingCostPer1kTokens: 0.00002,
  /** Bytes per stored vector when bytes_per_vector is unset (1536-dim float32 + metadata). */
  bytesPerVector: 2_000,
  /** Cache discount when cached_input price is unset: 90% off standard. */
  cacheReadDiscount: 0.1,
  /** Batch discount when batch_input/output price is unset: 50% off standard. */
  batchDiscount: 0.5,
  /** Peak-to-average request ratio when not specified. */
  peakRatio: 3,
} as const;

// ── Helpers ───────────────────────────────────────────────────────────────────

function blendedInputCostPer1k(
  cm: NonNullable<Tool["cost_model"]>,
  cacheHitRate: number,
  batchPct: number
): number {
  const std = cm.input_cost_per_1k_tokens ?? 0;
  const cached = cm.cached_input_cost_per_1k_tokens ?? std * DEFAULTS.cacheReadDiscount;
  const batch = cm.batch_input_cost_per_1k_tokens ?? std * DEFAULTS.batchDiscount;
  // Cache-blend the realtime price (cache discount applies on standard input);
  // batch-blend across the two channels.
  const realtimeBlended = cacheHitRate * cached + (1 - cacheHitRate) * std;
  return batchPct * batch + (1 - batchPct) * realtimeBlended;
}

function blendedOutputCostPer1k(cm: NonNullable<Tool["cost_model"]>, batchPct: number): number {
  const std = cm.output_cost_per_1k_tokens ?? 0;
  const batch = cm.batch_output_cost_per_1k_tokens ?? std * DEFAULTS.batchDiscount;
  return batchPct * batch + (1 - batchPct) * std;
}

function tokenCostPerRequest(
  cm: NonNullable<Tool["cost_model"]>,
  avgInputTokens: number,
  avgOutputTokens: number,
  cacheHitRate: number,
  batchPct: number
): number {
  const inRate = blendedInputCostPer1k(cm, cacheHitRate, batchPct);
  const outRate = blendedOutputCostPer1k(cm, batchPct);
  return (avgInputTokens / 1000) * inRate + (avgOutputTokens / 1000) * outRate;
}

function isUnprojected(tool: Tool | undefined): boolean {
  if (!tool?.cost_model) return false;
  const cm = tool.cost_model;
  if (cm.type === "usage_based") return true;
  if (cm.type === "per_call" && cm.cost_per_call == null) return true;
  return false;
}

// ── Per-tool monthly cost ─────────────────────────────────────────────────────

/**
 * Compute one tool's monthly cost given context. Pure dispatch on cost_model.type.
 *
 * Context fields:
 *   monthlyRequests — used by per_token, per_call, per_event, per_vector_query
 *   avgInputTokens / avgOutputTokens — per_token
 *   cacheHitRate / batchPct — per_token blending
 *   vectorCount — per_vector_query storage
 */
export interface CostContext {
  monthlyRequests: number;
  avgInputTokens: number;
  avgOutputTokens: number;
  cacheHitRate: number;
  batchPct: number;
  vectorCount: number;
}

export function computeToolMonthlyCost(tool: Tool, ctx: CostContext): number {
  const cm = tool.cost_model;
  if (!cm) return 0;

  switch (cm.type) {
    case "free":
      return 0;

    case "per_token":
      return (
        ctx.monthlyRequests *
        tokenCostPerRequest(
          cm,
          ctx.avgInputTokens,
          ctx.avgOutputTokens,
          ctx.cacheHitRate,
          ctx.batchPct
        )
      );

    case "flat":
      return cm.cost_per_month_base ?? 0;

    case "per_seat":
      return cm.cost_per_month_base ?? cm.cost_per_seat ?? 0;

    case "per_call":
      return ctx.monthlyRequests * (cm.cost_per_call ?? 0);

    case "per_event":
      return ctx.monthlyRequests * (cm.cost_per_event ?? 0);

    case "per_vector_query": {
      const bytesPerVector = tool.bytes_per_vector ?? DEFAULTS.bytesPerVector;
      const gbStored = (ctx.vectorCount * bytesPerVector) / 1024 ** 3;
      const storage = gbStored * (cm.storage_cost_per_gb_month ?? 0);
      const queries = (ctx.monthlyRequests / 1_000_000) * (cm.query_cost_per_million ?? 0);
      const subtotal = storage + queries;
      return Math.max(subtotal, cm.min_monthly_cost ?? 0);
    }

    case "usage_based":
      return 0;
  }
}

// ── Latency computation ───────────────────────────────────────────────────────

function llmLatency(
  tool: Tool | undefined,
  avgOutputTokens: number
): { ttft: number; generation: number } {
  const ttft = tool?.ttft_p50_ms ?? tool?.latency_p50_ms ?? DEFAULTS.ttftMs;
  const throughput = tool?.output_tokens_per_second ?? DEFAULTS.throughputTokPerSec;
  const generation = (avgOutputTokens / throughput) * 1000;
  return { ttft, generation };
}

export function computeLatency(
  input: SimulationInput,
  tools: Tool[]
): { totalMs: number; stages: LatencyByStage; breakdown: Record<string, number> } {
  const stages: LatencyByStage = {
    guardrails: 0,
    embedding: 0,
    vector: 0,
    ttft: 0,
    generation: 0,
    framework: 0,
  };

  if (input.stack.guardrails) {
    const tool = tools.find((t) => t.id === input.stack.guardrails);
    stages.guardrails = tool?.latency_p50_ms ?? DEFAULTS.guardrailsMs;
  }

  if (input.useCase === "rag" && input.stack.vectorDb) {
    // Embedding generation precedes vector retrieval.
    if (input.stack.embedding) {
      const tool = tools.find((t) => t.id === input.stack.embedding);
      stages.embedding = tool?.latency_p50_ms ?? DEFAULTS.embeddingMs;
    } else {
      stages.embedding = DEFAULTS.embeddingMs;
    }
    const vectorTool = tools.find((t) => t.id === input.stack.vectorDb);
    stages.vector = vectorTool?.latency_p50_ms ?? DEFAULTS.vectorMs;
  }

  const llmTool = tools.find((t) => t.id === input.stack.llm);
  const { ttft, generation } = llmLatency(llmTool, input.avgOutputTokens);
  stages.ttft = ttft;
  stages.generation = generation;

  if (input.stack.framework) {
    const tool = tools.find((t) => t.id === input.stack.framework);
    stages.framework = tool?.latency_p50_ms ?? DEFAULTS.frameworkMs;
  }

  const totalMs =
    stages.guardrails +
    stages.embedding +
    stages.vector +
    stages.ttft +
    stages.generation +
    stages.framework;

  // Legacy breakdown mirror for older UI components (LatencyBreakdown reads this shape).
  const breakdown: Record<string, number> = {};
  if (stages.guardrails > 0) breakdown.guardrails = stages.guardrails;
  if (stages.embedding > 0) breakdown.embedding = stages.embedding;
  if (stages.vector > 0) breakdown.vector = stages.vector;
  breakdown.ttft = stages.ttft;
  breakdown.generation = stages.generation;
  if (stages.framework > 0) breakdown.framework = stages.framework;

  return { totalMs, stages, breakdown };
}

// ── Rate-limit check ──────────────────────────────────────────────────────────

function isRateLimited(
  llmTool: Tool | undefined,
  monthlyRequests: number,
  avgInputTokens: number,
  avgOutputTokens: number,
  peakRatio: number
): boolean {
  if (!llmTool) return false;
  // Average requests per minute. (Month ≈ 43,800 minutes.)
  const avgRpm = monthlyRequests / (30 * 24 * 60);
  // Tokens (input + output) per minute at average load.
  const tokensPerReq = avgInputTokens + avgOutputTokens;
  const avgTpm = avgRpm * tokensPerReq;
  // Peak demand spikes above the average.
  const peakRpm = avgRpm * peakRatio;
  const peakTpm = avgTpm * peakRatio;
  if (llmTool.max_rpm != null && peakRpm > llmTool.max_rpm) return true;
  if (llmTool.max_tpm != null && peakTpm > llmTool.max_tpm) return true;
  return false;
}

// ── Main simulation ───────────────────────────────────────────────────────────

export function simulate(input: SimulationInput, tools: Tool[]): SimulationResult {
  const { useCase, requestsPerUserPerDay, avgInputTokens, avgOutputTokens, stack } = input;
  const cacheHitRate = clamp01(input.cacheHitRate ?? 0);
  const batchPct = clamp01(input.batchPct ?? 0);
  const vectorCount = Math.max(0, input.vectorCount ?? 0);
  const embedTokensPerQuery = Math.max(
    1,
    input.embeddingTokensPerQuery ?? DEFAULTS.embeddingTokensPerQuery
  );
  const peakRatio = Math.max(1, input.peakToAverageRatio ?? DEFAULTS.peakRatio);
  const routerCheapPct = clamp01(stack.routerCheapPct ?? 0);

  const llmTool = tools.find((t) => t.id === stack.llm);
  const cheapLlmTool = stack.routerCheapLlm
    ? tools.find((t) => t.id === stack.routerCheapLlm)
    : undefined;
  const embeddingTool = stack.embedding ? tools.find((t) => t.id === stack.embedding) : undefined;
  const vectorTool = stack.vectorDb ? tools.find((t) => t.id === stack.vectorDb) : undefined;
  const frameworkTool = stack.framework ? tools.find((t) => t.id === stack.framework) : undefined;
  const evalTool = stack.eval ? tools.find((t) => t.id === stack.eval) : undefined;
  const guardrailsTool = stack.guardrails
    ? tools.find((t) => t.id === stack.guardrails)
    : undefined;

  const { totalMs: latencyMs, stages, breakdown: latencyBreakdown } = computeLatency(input, tools);

  const snapshots: SimulationSnapshot[] = SCALE_STEPS.map((users) => {
    const monthlyRequests = users * requestsPerUserPerDay * 30;

    const ctx: CostContext = {
      monthlyRequests,
      avgInputTokens,
      avgOutputTokens,
      cacheHitRate,
      batchPct,
      vectorCount,
    };

    const costBreakdown: Record<string, number> = {};
    const costByLayer: CostByLayer = {
      llm: 0,
      embedding: 0,
      vector: 0,
      framework: 0,
      eval: 0,
      guardrails: 0,
    };

    // LLM cost — blend across router if a cheap model is configured.
    if (llmTool) {
      const mainShare = 1 - routerCheapPct;
      const mainCost = computeToolMonthlyCost(llmTool, {
        ...ctx,
        monthlyRequests: ctx.monthlyRequests * mainShare,
      });
      costBreakdown[stack.llm] = mainCost;
      costByLayer.llm += mainCost;
    }
    if (cheapLlmTool && stack.routerCheapLlm) {
      const cheapCost = computeToolMonthlyCost(cheapLlmTool, {
        ...ctx,
        monthlyRequests: ctx.monthlyRequests * routerCheapPct,
      });
      costBreakdown[stack.routerCheapLlm] = cheapCost;
      costByLayer.llm += cheapCost;
    }

    // Embedding cost (RAG only). Cost driven by per-query embedding tokens.
    if (useCase === "rag") {
      const embedReqCtx: CostContext = {
        ...ctx,
        avgInputTokens: embedTokensPerQuery,
        avgOutputTokens: 0,
        cacheHitRate: 0,
        batchPct: 0,
      };
      let embeddingCost = 0;
      if (embeddingTool) {
        embeddingCost = computeToolMonthlyCost(embeddingTool, embedReqCtx);
        costBreakdown[stack.embedding!] = embeddingCost;
      } else {
        // Default to text-embedding-3-small economics when no tool selected.
        embeddingCost =
          monthlyRequests * (embedTokensPerQuery / 1000) * DEFAULTS.embeddingCostPer1kTokens;
      }
      costByLayer.embedding = embeddingCost;
    }

    // Vector DB cost (RAG only).
    if (useCase === "rag" && vectorTool && stack.vectorDb) {
      const vectorCost = computeToolMonthlyCost(vectorTool, ctx);
      costBreakdown[stack.vectorDb] = vectorCost;
      costByLayer.vector = vectorCost;
    }

    // Framework cost (typically flat).
    if (frameworkTool && stack.framework) {
      const frameworkCost = computeToolMonthlyCost(frameworkTool, ctx);
      costBreakdown[stack.framework] = frameworkCost;
      costByLayer.framework = frameworkCost;
    }

    // Eval cost (per-event).
    if (evalTool && stack.eval) {
      const evalCost = computeToolMonthlyCost(evalTool, ctx);
      costBreakdown[stack.eval] = evalCost;
      costByLayer.eval = evalCost;
    }

    // Guardrails cost (per-call).
    if (guardrailsTool && stack.guardrails) {
      const guardrailsCost = computeToolMonthlyCost(guardrailsTool, ctx);
      costBreakdown[stack.guardrails] = guardrailsCost;
      costByLayer.guardrails = guardrailsCost;
    }

    const monthlyCostUSD =
      costByLayer.llm +
      costByLayer.embedding +
      costByLayer.vector +
      costByLayer.framework +
      costByLayer.eval +
      costByLayer.guardrails;

    return {
      users,
      monthlyRequests,
      monthlyCostUSD,
      costPerRequest: monthlyRequests > 0 ? monthlyCostUSD / monthlyRequests : 0,
      costPerUser: users > 0 ? monthlyCostUSD / users : 0,
      avgLatencyMs: latencyMs,
      costBreakdown,
      costByLayer,
      latencyByStage: stages,
      latencyBreakdown,
    };
  });

  // ── Breaking points ────────────────────────────────────────────────────────

  const breakingPoints: BreakingPoint[] = [];
  const firedCostMilestones = new Set<number>();
  let latencyBreachFired = false;
  let llmDominanceFired = false;
  let rateLimitFired = false;
  let rateLimitAtUsers: number | null = null;

  const latencyCeiling = LATENCY_CEILING_MS[useCase];
  let ttftBreachFired = false;
  for (const snap of snapshots) {
    if (!latencyBreachFired && snap.avgLatencyMs > latencyCeiling) {
      breakingPoints.push({
        users: snap.users,
        type: "latency",
        message: `Total response exceeds ${formatMs(latencyCeiling)} (${formatMs(snap.avgLatencyMs)}) — past what ${useCase} users tolerate`,
        recommendation:
          "Drop output tokens, switch to a higher-throughput model (Cerebras ~800 tok/s, Groq ~500 tok/s, Gemini Flash ~120 tok/s), or stream the response so users see progress.",
      });
      latencyBreachFired = true;
    }
    if (!ttftBreachFired && snap.latencyByStage.ttft > TTFT_SLOW_MS) {
      breakingPoints.push({
        users: snap.users,
        type: "latency",
        message: `Time-to-first-token is ${formatMs(snap.latencyByStage.ttft)} — feels unresponsive even with streaming`,
        recommendation:
          "Switch to a provider with lower TTFT (OpenAI, Groq, Gemini), reduce prompt size, or enable prompt caching to skip context processing.",
      });
      ttftBreachFired = true;
    }

    for (const milestone of [1_000, 5_000, 20_000, 100_000]) {
      if (!firedCostMilestones.has(milestone) && snap.monthlyCostUSD >= milestone) {
        breakingPoints.push({
          users: snap.users,
          type: "cost",
          message: `Cost crosses $${milestone.toLocaleString()}/mo at ${formatUsers(snap.users)}`,
          recommendation:
            "Move to a cheaper model, enable prompt caching, or send non-real-time traffic via the batch API.",
        });
        firedCostMilestones.add(milestone);
      }
    }

    const llmCost = snap.costByLayer.llm;
    const otherCosts = snap.monthlyCostUSD - llmCost;
    if (
      !llmDominanceFired &&
      otherCosts > 0 &&
      snap.monthlyCostUSD > 100 &&
      llmCost / snap.monthlyCostUSD > 0.8
    ) {
      breakingPoints.push({
        users: snap.users,
        type: "architecture",
        message: `LLM is ${Math.round((llmCost / snap.monthlyCostUSD) * 100)}% of cost at ${formatUsers(snap.users)} — caching/routing has high leverage`,
        recommendation:
          "Add prompt caching (90% off cached input) or route easy queries to a cheaper model.",
      });
      llmDominanceFired = true;
    }

    if (
      !rateLimitFired &&
      isRateLimited(llmTool, snap.monthlyRequests, avgInputTokens, avgOutputTokens, peakRatio)
    ) {
      breakingPoints.push({
        users: snap.users,
        type: "rate_limit",
        message: `Peak load exceeds provider rate limit at ${formatUsers(snap.users)} (${peakRatio}× peak/avg)`,
        recommendation:
          "Move to a higher provider tier, distribute across multiple API keys, or buffer non-real-time traffic via batch API.",
      });
      rateLimitFired = true;
      rateLimitAtUsers = snap.users;
    }
  }

  // ── Kill conditions ────────────────────────────────────────────────────────

  const killConditions: KillCondition[] = [];

  if (useCase === "rag" && !stack.vectorDb) {
    killConditions.push({
      type: "missing_vector_db",
      message: "RAG without a vector store",
      recommendation: "Add a vector database (Qdrant, Pinecone, or pgvector) for retrieval.",
    });
  }

  if (!stack.eval) {
    killConditions.push({
      type: "no_eval_layer",
      message: "No eval layer in stack",
      recommendation:
        "Add Langfuse, Braintrust, or DeepEval to catch quality regressions before users do.",
    });
  }

  const unprojectedNames = [
    llmTool,
    vectorTool,
    frameworkTool,
    embeddingTool,
    evalTool,
    guardrailsTool,
    cheapLlmTool,
  ]
    .filter((t): t is Tool => !!t && isUnprojected(t))
    .map((t) => t.name);
  if (unprojectedNames.length > 0) {
    killConditions.push({
      type: "unprojected_cost",
      message: `Cost projection unavailable for: ${unprojectedNames.join(", ")}`,
      recommendation:
        "These tools have usage-based or per-call pricing without a published per-unit rate. Contact their team for volume estimates.",
    });
  }

  // ── Bottleneck verdict ────────────────────────────────────────────────────

  const lastSnap = snapshots[snapshots.length - 1];
  const { bottleneck, bottleneckMessage } = diagnoseBottleneck(
    useCase,
    snapshots,
    lastSnap,
    latencyBreachFired,
    rateLimitFired,
    rateLimitAtUsers,
    llmCost(snapshots)
  );

  return {
    snapshots,
    breakingPoints,
    killConditions,
    bottleneck,
    bottleneckMessage,
    rateLimitAtUsers,
  };
}

// ── Bottleneck diagnosis ──────────────────────────────────────────────────────

function llmCost(snapshots: SimulationSnapshot[]): number {
  return snapshots.reduce((m, s) => Math.max(m, s.costByLayer.llm), 0);
}

function diagnoseBottleneck(
  useCase: SimulationUseCase,
  snapshots: SimulationSnapshot[],
  lastSnap: SimulationSnapshot | undefined,
  latencyBreached: boolean,
  rateLimitFired: boolean,
  rateLimitAtUsers: number | null,
  maxLlmCost: number
): { bottleneck: BottleneckType; bottleneckMessage: string } {
  if (!lastSnap || lastSnap.monthlyCostUSD === 0) {
    return {
      bottleneck: "none",
      bottleneckMessage:
        "All free/OSS — cost projection isn't useful; check latency and structural risks.",
    };
  }
  if (rateLimitFired && rateLimitAtUsers !== null) {
    return {
      bottleneck: "rate_limit",
      bottleneckMessage: `Rate-limit bound — the provider tier caps you at ${formatUsers(rateLimitAtUsers)} users before you need to upgrade or split keys.`,
    };
  }
  const costHigh = lastSnap.monthlyCostUSD >= 20_000;
  if (latencyBreached && costHigh) {
    return {
      bottleneck: "balanced",
      bottleneckMessage:
        "Cost- and latency-bound — both dimensions are problematic at scale. Switching to a smaller, faster model is the highest-leverage move.",
    };
  }
  if (latencyBreached) {
    return {
      bottleneck: "latency",
      bottleneckMessage: `Latency-bound — p50 response crosses the ${useCase} comfort ceiling. Output tokens dominate, so throughput matters more than TTFT.`,
    };
  }
  if (costHigh) {
    const llmShareAtMax = maxLlmCost / lastSnap.monthlyCostUSD;
    if (llmShareAtMax > 0.7) {
      return {
        bottleneck: "cost",
        bottleneckMessage: `Cost-bound — LLM tokens drive ${Math.round(llmShareAtMax * 100)}% of spend at 1M users. Caching and routing are your levers.`,
      };
    }
    return {
      bottleneck: "cost",
      bottleneckMessage: `Cost-bound — spend exceeds $20k/mo at 1M users.`,
    };
  }
  return {
    bottleneck: "none",
    bottleneckMessage: "No bottleneck within the projected range — your stack scales cleanly.",
  };
}

// ── Helpers ───────────────────────────────────────────────────────────────────

function clamp01(n: number): number {
  if (!Number.isFinite(n)) return 0;
  return Math.min(1, Math.max(0, n));
}

function formatUsers(n: number): string {
  return n >= 1_000_000 ? `${n / 1_000_000}M users` : `${(n / 1_000).toFixed(0)}k users`;
}

function formatMs(ms: number): string {
  return ms >= 1000 ? `${(ms / 1000).toFixed(1)}s` : `${Math.round(ms)}ms`;
}
