/**
 * AI Stack Simulator — pure computation engine (AIC-126).
 *
 * Given a stack + scale inputs and the tool catalog, projects monthly cost and
 * latency across nine scale steps and detects architectural breaking points.
 *
 * The engine is pure: it takes the tool array as an argument so the same code
 * is used by the route handler (which loads from the DB), unit tests, and any
 * future caller. Live latency/pricing data lives only in the DB — the
 * sync-benchmarks cron writes there and the route reads from there.
 */

import type { Tool } from "@/lib/types";

// ── Public types ──────────────────────────────────────────────────────────────

export type SimulationUseCase = "chatbot" | "rag" | "agent" | "custom";

export interface SimulationInput {
  useCase: SimulationUseCase;
  monthlyUsers: number;
  requestsPerUserPerDay: number;
  /** Tokens consumed as model input (prompt + retrieved context) per request. */
  avgInputTokens: number;
  /** Tokens generated by the model per request. */
  avgOutputTokens: number;
  stack: {
    llm: string; // tool id
    vectorDb?: string; // tool id
    framework?: string; // tool id
  };
}

export interface SimulationSnapshot {
  users: number;
  monthlyCostUSD: number;
  avgLatencyMs: number;
  /** Per-tool monthly cost in USD */
  costBreakdown: Record<string, number>;
  /** Per-layer latency contribution in ms */
  latencyBreakdown: Record<string, number>;
}

export interface BreakingPoint {
  users: number;
  type: "latency" | "cost" | "architecture";
  message: string;
}

export interface KillCondition {
  type: string;
  message: string;
  recommendation?: string;
}

export interface SimulationResult {
  snapshots: SimulationSnapshot[];
  breakingPoints: BreakingPoint[];
  killConditions: KillCondition[];
}

// ── Scale steps ───────────────────────────────────────────────────────────────

export const SCALE_STEPS = [
  1_000, 5_000, 10_000, 25_000, 50_000, 100_000, 250_000, 500_000, 1_000_000,
];

// ── Per-use-case token defaults ───────────────────────────────────────────────
//
// Sensible starting values UIs can use to populate the input form. RAG inflates
// input because retrieved context dominates; chatbot is balanced; agent loops
// accumulate context as tools fire. Engine itself stays agnostic — it only uses
// whatever input/output counts the caller passes in.

export const TOKEN_DEFAULTS: Record<
  SimulationUseCase,
  { inputTokens: number; outputTokens: number }
> = {
  chatbot: { inputTokens: 400, outputTokens: 600 },
  rag: { inputTokens: 3_000, outputTokens: 400 },
  agent: { inputTokens: 1_500, outputTokens: 800 },
  custom: { inputTokens: 1_000, outputTokens: 500 },
};

// ── Latency defaults ──────────────────────────────────────────────────────────
//
// Fallbacks when a tool has no latency_p50_ms. AA-tracked LLM providers get
// real TTFT written by the sync-benchmarks cron; static tools (inference
// providers, vector DBs, frameworks) carry their value in tools.json.

const DEFAULT_LLM_LATENCY_MS = 800;
const DEFAULT_VECTOR_LATENCY_MS = 80;
const DEFAULT_FRAMEWORK_LATENCY_MS = 100;

// ── Cost computation ──────────────────────────────────────────────────────────

/**
 * Compute monthly USD cost for a single tool at a given request volume.
 * Returns 0 for OSS/free tools — they are correctly treated as zero-cost.
 * Returns 0 for usage_based and unparameterised per_call tools — flagged
 * separately in kill conditions.
 */
export function computeToolMonthlyCost(
  tool: Tool,
  monthlyRequests: number,
  avgInputTokens: number,
  avgOutputTokens: number
): number {
  const cm = tool.cost_model;
  if (!cm) return 0;

  switch (cm.type) {
    case "free":
      return 0;

    case "per_token": {
      const inputCost = (avgInputTokens / 1000) * (cm.input_cost_per_1k_tokens ?? 0);
      const outputCost = (avgOutputTokens / 1000) * (cm.output_cost_per_1k_tokens ?? 0);
      return monthlyRequests * (inputCost + outputCost);
    }

    case "flat":
      return cm.cost_per_month_base ?? 0;

    case "per_seat":
      // In a backend API context seats don't scale with users — treat as flat infra cost
      return cm.cost_per_month_base ?? cm.cost_per_seat ?? 0;

    case "per_call":
      // Use the published per-call rate when present; otherwise unprojected (flagged below).
      return monthlyRequests * (cm.cost_per_call ?? 0);

    case "usage_based":
      // No published per-unit rate — cannot project. Flagged in kill conditions.
      return 0;
  }
}

// ── Latency computation ───────────────────────────────────────────────────────

export function computeLatency(
  stack: SimulationInput["stack"],
  tools: Tool[]
): {
  totalMs: number;
  breakdown: Record<string, number>;
} {
  const breakdown: Record<string, number> = {};

  const llmTool = tools.find((t) => t.id === stack.llm);
  breakdown["llm"] = llmTool?.latency_p50_ms ?? DEFAULT_LLM_LATENCY_MS;

  if (stack.vectorDb) {
    const vectorTool = tools.find((t) => t.id === stack.vectorDb);
    breakdown["vector"] = vectorTool?.latency_p50_ms ?? DEFAULT_VECTOR_LATENCY_MS;
  }

  if (stack.framework) {
    const frameworkTool = tools.find((t) => t.id === stack.framework);
    breakdown["framework"] = frameworkTool?.latency_p50_ms ?? DEFAULT_FRAMEWORK_LATENCY_MS;
  }

  const totalMs = Object.values(breakdown).reduce((sum, ms) => sum + ms, 0);
  return { totalMs, breakdown };
}

// ── Unprojected detection ─────────────────────────────────────────────────────

function isUnprojected(tool: Tool | undefined): boolean {
  if (!tool?.cost_model) return false;
  const cm = tool.cost_model;
  if (cm.type === "usage_based") return true;
  if (cm.type === "per_call" && cm.cost_per_call == null) return true;
  return false;
}

// ── Main simulation ───────────────────────────────────────────────────────────

export function simulate(input: SimulationInput, tools: Tool[]): SimulationResult {
  const { useCase, requestsPerUserPerDay, avgInputTokens, avgOutputTokens, stack } = input;

  const llmTool = tools.find((t) => t.id === stack.llm);
  const vectorTool = stack.vectorDb ? tools.find((t) => t.id === stack.vectorDb) : undefined;
  const frameworkTool = stack.framework ? tools.find((t) => t.id === stack.framework) : undefined;

  const { totalMs: latencyMs, breakdown: latencyBreakdown } = computeLatency(stack, tools);

  // ── Snapshots ──────────────────────────────────────────────────────────────

  const snapshots: SimulationSnapshot[] = SCALE_STEPS.map((users) => {
    const monthlyRequests = users * requestsPerUserPerDay * 30;
    const costBreakdown: Record<string, number> = {};

    if (llmTool) {
      costBreakdown[stack.llm] = computeToolMonthlyCost(
        llmTool,
        monthlyRequests,
        avgInputTokens,
        avgOutputTokens
      );
    }
    if (vectorTool && stack.vectorDb) {
      costBreakdown[stack.vectorDb] = computeToolMonthlyCost(
        vectorTool,
        monthlyRequests,
        avgInputTokens,
        avgOutputTokens
      );
    }
    if (frameworkTool && stack.framework) {
      costBreakdown[stack.framework] = computeToolMonthlyCost(
        frameworkTool,
        monthlyRequests,
        avgInputTokens,
        avgOutputTokens
      );
    }

    const monthlyCostUSD = Object.values(costBreakdown).reduce((s, v) => s + v, 0);

    return { users, monthlyCostUSD, avgLatencyMs: latencyMs, costBreakdown, latencyBreakdown };
  });

  // ── Breaking points ────────────────────────────────────────────────────────

  const breakingPoints: BreakingPoint[] = [];
  const firedCostMilestones = new Set<number>();
  let latencyBreachFired = false;
  let llmDominanceFired = false;

  for (const snap of snapshots) {
    if (!latencyBreachFired && snap.avgLatencyMs > 2000) {
      breakingPoints.push({
        users: snap.users,
        type: "latency",
        message: `Latency risk at ${formatUsers(snap.users)} — avg response exceeds 2s`,
      });
      latencyBreachFired = true;
    }

    for (const milestone of [1_000, 5_000, 20_000]) {
      if (!firedCostMilestones.has(milestone) && snap.monthlyCostUSD >= milestone) {
        breakingPoints.push({
          users: snap.users,
          type: "cost",
          message: `Cost crosses $${milestone.toLocaleString()}/mo at ${formatUsers(snap.users)}`,
        });
        firedCostMilestones.add(milestone);
      }
    }

    const llmCost = snap.costBreakdown[stack.llm] ?? 0;
    const hasOtherCosts = snap.monthlyCostUSD - llmCost > 0;
    if (
      !llmDominanceFired &&
      hasOtherCosts &&
      snap.monthlyCostUSD > 100 &&
      llmCost / snap.monthlyCostUSD > 0.8
    ) {
      breakingPoints.push({
        users: snap.users,
        type: "architecture",
        message: `LLM cost dominates (${Math.round((llmCost / snap.monthlyCostUSD) * 100)}% of total) at ${formatUsers(snap.users)} — consider adding a caching layer`,
      });
      llmDominanceFired = true;
    }
  }

  // ── Kill conditions ────────────────────────────────────────────────────────

  const killConditions: KillCondition[] = [];

  if (useCase === "rag" && !stack.vectorDb) {
    killConditions.push({
      type: "missing_vector_db",
      message: "RAG without a vector store",
      recommendation: "Add a vector database (Qdrant, Pinecone, or pgvector) for retrieval.",
    });
  }

  killConditions.push({
    type: "no_eval_layer",
    message: "No eval layer in stack",
    recommendation:
      "Add Langfuse, Braintrust, or DeepEval to catch quality regressions before users do.",
  });

  const unprojectedNames = [llmTool, vectorTool, frameworkTool]
    .filter((t): t is Tool => !!t && isUnprojected(t))
    .map((t) => t.name);

  if (unprojectedNames.length > 0) {
    killConditions.push({
      type: "unprojected_cost",
      message: `Cost projection unavailable for: ${unprojectedNames.join(", ")}`,
      recommendation:
        "These tools have usage-based or per-call pricing without a published per-unit rate. Contact their team for volume estimates.",
    });
  }

  return { snapshots, breakingPoints, killConditions };
}

// ── Helpers ───────────────────────────────────────────────────────────────────

function formatUsers(n: number): string {
  return n >= 1_000_000 ? `${n / 1_000_000}M users` : `${(n / 1_000).toFixed(0)}k users`;
}
