import { Tool, CategoryId, STACK_LAYERS } from "./types";

// Ordered position of each category in the canonical stack
const LAYER_ORDER: CategoryId[] = STACK_LAYERS.flatMap((l) => l.categories);

// Autonomy level shown on each Builder slot
export const SLOT_AUTONOMY: Record<string, { label: string; color: string }> = {
  "code-editor":       { label: "you drive",          color: "#7c6bff" },
  "cli-agent":         { label: "you direct",          color: "#a29bfe" },
  "swe-agent":         { label: "AI runs autonomously", color: "#ff6b6b" },
  "agent-framework":   { label: "you define, AI traverses", color: "#fdcb6e" },
  "orchestration":     { label: "deterministic + AI",  color: "#26de81" },
  "model-router":      { label: "routes & normalizes", color: "#4ecdc4" },
  "inference":         { label: "pure computation",    color: "#4ecdc4" },
  "vector-db":         { label: "memory layer",        color: "#00d4aa" },
  "observability":     { label: "passive observer",    color: "#fd9644" },
  "design-to-code":    { label: "AI generates",        color: "#ff9f43" },
  "devops-automation": { label: "AI reviews",          color: "#fd9644" },
  "mcp-infra":         { label: "extends reach",       color: "#a29bfe" },
  "prompt-eval":       { label: "measures quality",    color: "#55efc4" },
  "docs":              { label: "auto-generated",      color: "#74b9ff" },
  "product-mgmt":      { label: "prioritizes signal",  color: "#fd79a8" },
  "specifications":    { label: "defines the contract", color: "#e17055" },
};

// Short verb fragment for the stack story narrative, per category
function verb(cat: CategoryId, isFirst: boolean): string {
  const map: Record<CategoryId, string> = {
    "coding-assistants": isFirst ? "You write in" : "assisted by",
    "autonomous-agents": "autonomous tasks go to",
    "agent-frameworks":  "agent logic runs in",
    "pipelines-rag":     "calls chain through",
    "llm-infra":         "powered by",
    "design":            "UI generated by",
    "devops":            "code reviewed by",
    "docs":              "docs by",
    "product-mgmt":      "roadmap in",
    "mcp":               "extended via",
    "prompt-eval":       "evals in",
    "specifications":    "spec defined in",
  };
  return map[cat] ?? "uses";
}

export function generateStackStory(tools: Tool[]): {
  flow: string;       // "Cursor → Claude Code → LangGraph → …"
  prose: string;      // natural-language explanation
} | null {
  if (tools.length < 2) return null;

  const sorted = [...tools].sort(
    (a, b) => LAYER_ORDER.indexOf(a.category) - LAYER_ORDER.indexOf(b.category)
  );

  const flow = sorted.map((t) => t.name).join(" → ");

  const proseFragments = sorted.map((t, i) =>
    `${verb(t.category, i === 0)} ${t.name}`
  );

  // Build a readable sentence with proper conjunctions
  let prose: string;
  if (proseFragments.length === 2) {
    prose = `${proseFragments[0]}, then ${proseFragments[1]}.`;
  } else {
    const last = proseFragments.pop()!;
    prose = `${proseFragments.join(", ")}, and ${last}.`;
  }
  // Capitalize
  prose = prose.charAt(0).toUpperCase() + prose.slice(1);

  return { flow, prose };
}
