import { Tool } from "./types";

// Canonical narrative order for tool slots — drives sort AND prose verb selection.
// Using slot (not category) because slots are already granular: llm-infra alone
// covers providers, routers, vector DBs, and observability, which all serve
// distinct roles in a stack story.
const SLOT_ORDER: string[] = [
  "specifications",
  "product-mgmt",
  "design-to-code", // UI is generated first; code editors then work with the output
  "code-editor",
  "cli-agent",
  "swe-agent",
  "browser-automation",
  "agent-framework",
  "orchestration",
  "model-router",
  "inference",
  "fine-tuning",
  "multimodal",
  "voice-ai",
  "vector-db",
  "mcp-infra",
  "observability",
  "devops-automation",
  "prompt-eval",
  "docs",
];

// Autonomy level shown on each Builder slot
export const SLOT_AUTONOMY: Record<string, { label: string; color: string }> = {
  "code-editor": { label: "you drive", color: "#7c6bff" },
  "cli-agent": { label: "you direct", color: "#a29bfe" },
  "swe-agent": { label: "AI runs autonomously", color: "#ff6b6b" },
  "browser-automation": { label: "AI controls browser", color: "#f0932b" },
  "agent-framework": { label: "you define, AI traverses", color: "#fdcb6e" },
  orchestration: { label: "deterministic + AI", color: "#26de81" },
  "model-router": { label: "routes & normalizes", color: "#4ecdc4" },
  inference: { label: "pure computation", color: "#4ecdc4" },
  "fine-tuning": { label: "custom model training", color: "#e84393" },
  multimodal: { label: "vision + language", color: "#6c5ce7" },
  "voice-ai": { label: "speech interface", color: "#00b894" },
  "vector-db": { label: "memory layer", color: "#00d4aa" },
  observability: { label: "passive observer", color: "#fd9644" },
  "design-to-code": { label: "AI generates", color: "#ff9f43" },
  "devops-automation": { label: "AI reviews", color: "#fd9644" },
  "mcp-infra": { label: "extends reach", color: "#a29bfe" },
  "prompt-eval": { label: "measures quality", color: "#55efc4" },
  docs: { label: "auto-generated", color: "#74b9ff" },
  "product-mgmt": { label: "prioritizes signal", color: "#fd79a8" },
  specifications: { label: "defines the contract", color: "#e17055" },
};

// Short verb fragment for the stack story narrative, per slot.
// Each slot has one distinct role in a stack so verbs don't repeat across tools.
function verb(slot: string, isFirst: boolean): string {
  const map: Record<string, string> = {
    specifications: isFirst ? "Spec defined in" : "spec in",
    "product-mgmt": isFirst ? "Roadmap in" : "roadmap in",
    "code-editor": isFirst ? "You write in" : "assisted by",
    "cli-agent": isFirst ? "Terminal tasks via" : "terminal tasks via",
    "swe-agent": isFirst ? "Autonomous work via" : "autonomous work via",
    "agent-framework": isFirst ? "Agent logic in" : "agent logic in",
    orchestration: isFirst ? "Calls chain through" : "chaining through",
    "model-router": isFirst ? "Routed via" : "routed via",
    inference: isFirst ? "Powered by" : "powered by",
    "fine-tuning": isFirst ? "Custom model via" : "fine-tuned with",
    multimodal: isFirst ? "Vision + language via" : "vision via",
    "voice-ai": isFirst ? "Voice powered by" : "voice via",
    "browser-automation": isFirst ? "Browser automated via" : "browser via",
    "vector-db": isFirst ? "Context from" : "context from",
    "mcp-infra": isFirst ? "Extended via" : "extended via",
    observability: isFirst ? "Traced by" : "traced by",
    "design-to-code": isFirst ? "UI generated by" : "UI generated by",
    "devops-automation": isFirst ? "Code quality via" : "code quality via",
    "prompt-eval": isFirst ? "Quality measured by" : "quality measured by",
    docs: isFirst ? "Docs by" : "docs by",
  };
  return map[slot] ?? (isFirst ? "Starts with" : "uses");
}

export function generateStackStory(tools: Tool[]): {
  flow: string; // "Cursor → Claude Code → LangGraph → …"
  prose: string; // natural-language explanation
} | null {
  if (tools.length < 2) return null;

  const sorted = [...tools].sort((a, b) => {
    const ai = SLOT_ORDER.indexOf(a.slot);
    const bi = SLOT_ORDER.indexOf(b.slot);
    return (ai === -1 ? 999 : ai) - (bi === -1 ? 999 : bi);
  });

  const flow = sorted.map((t) => t.name).join(" → ");

  const proseFragments = sorted.map((t, i) => `${verb(t.slot, i === 0)} ${t.name}`);

  // Build a readable sentence with proper conjunctions
  let prose: string;
  if (proseFragments.length === 2) {
    prose = `${proseFragments[0]}, then ${proseFragments[1]}.`;
  } else {
    const last = proseFragments.pop()!;
    prose = `${proseFragments.join(", ")}, and ${last}.`;
  }
  // Capitalize
  prose = prose.charAt(0).toUpperCase() + prose.slice(1);

  return { flow, prose };
}
